# Generated by Django 4.2.19 on 2025-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobookmark',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
